### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ollpu** [ollpu/time-window#1]
- [x] Sharing of shows
  - [ ] When someone starts the show, don't allow anyone else to start the same show
  - [x] Implement proper show-stop (alert clients etc)
- [ ] Shows shows shows
  - [x] Add a possibility to schedule the start of a show
  - [ ] Playback preferences (go-to-next automatically, etc)
  - [ ] Optional sound notifications
  - [ ] Tell the host if the connection to the server has failed
- [ ] Domain
  - [ ] Buy the domain
  - [ ] Configure the domain
  - [ ] SSL while we're at it
  - [ ] IPv6
- [x] User account modification
  - [ ] Password recovery by email
- [ ] Make a more welcoming login page
